import { Hono } from "hono";

// The ComeRico backend, running on Cloudflare Workers.
//
// This file is intentionally thin: it wires middleware and mounts route
// modules. Business logic lives in src/features/**, HTTP mapping in
// src/routes/**, mirroring the "endpoints map HTTP to handlers" rule from the
// original ASP.NET Core backend.

// `Env` is generated by `wrangler types` into worker-configuration.d.ts from
// the bindings in wrangler.jsonc (run `pnpm cf-typegen` after changing them).
const app = new Hono<{ Bindings: Env }>();

// Liveness probe — replaced/extended as real routes land.
app.get("/api/health", (c) => c.json({ status: "ok" }));

export default app;
