namespace ComeRico.Core.Domain.Entities;

public class ShoppingItem : IHasHousehold
{
    public Guid Id { get; private set; } = Guid.NewGuid();
    public Guid HouseholdId { get; private set; }
    public string Name { get; private set; } = string.Empty;
    public decimal? Amount { get; private set; }
    public MeasurementUnit? Unit { get; private set; }
    public bool IsPurchased { get; private set; }
    public bool IsAutoGenerated { get; private set; }

    /// <summary>
    /// Monday of the week this auto-generated item was consolidated for.
    /// Regenerating a week's list replaces only its auto items and leaves
    /// manual entries (GeneratedForWeekStart == null) untouched.
    /// </summary>
    public DateOnly? GeneratedForWeekStart { get; private set; }

    public DateTime CreatedAt { get; private set; } = DateTime.UtcNow;

    public Household Household { get; private set; } = null!;

    private ShoppingItem() { }

    public static ShoppingItem CreateManual(Guid householdId, string name, decimal? amount, MeasurementUnit? unit) =>
        new()
        {
            HouseholdId = householdId,
            Name = name,
            Amount = amount,
            Unit = unit,
        };

    public static ShoppingItem CreateGenerated(
        Guid householdId,
        string name,
        decimal amount,
        MeasurementUnit unit,
        DateOnly weekStart
    ) =>
        new()
        {
            HouseholdId = householdId,
            Name = name,
            Amount = amount,
            Unit = unit,
            IsAutoGenerated = true,
            GeneratedForWeekStart = weekStart,
        };

    public void SetPurchased(bool isPurchased) => IsPurchased = isPurchased;
}
