using ComeRico.Core.Domain.Entities;
using ComeRico.Core.Features.Shopping.Queries;
using ComeRico.Core.Interfaces;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace ComeRico.Core.Features.Shopping.Commands;

/// <summary>
/// Consolidates the ingredients of every meal planned in the week containing
/// <paramref name="AnyDateInWeek"/> (Monday–Sunday) into shopping items,
/// summing amounts by ingredient name + unit. Replaces the auto-generated
/// items of that week; manual items are never touched.
/// </summary>
public sealed record GenerateShoppingListCommand(DateOnly AnyDateInWeek) : IRequest<IReadOnlyList<ShoppingItemDto>>;

public sealed class GenerateShoppingListCommandHandler(IAppDbContext dbContext, ITenantService tenantService)
    : IRequestHandler<GenerateShoppingListCommand, IReadOnlyList<ShoppingItemDto>>
{
    public async Task<IReadOnlyList<ShoppingItemDto>> Handle(
        GenerateShoppingListCommand request,
        CancellationToken cancellationToken
    )
    {
        var daysSinceMonday = ((int)request.AnyDateInWeek.DayOfWeek + 6) % 7;
        var weekStart = request.AnyDateInWeek.AddDays(-daysSinceMonday);
        var weekEnd = weekStart.AddDays(6);

        var plannedIngredients = await dbContext
            .MealPlans.Where(m => m.Date >= weekStart && m.Date <= weekEnd)
            .SelectMany(m => m.Dish.Ingredients)
            .Select(i => new
            {
                i.Name,
                i.Amount,
                i.Unit,
            })
            .ToListAsync(cancellationToken);

        if (plannedIngredients.Count == 0)
            throw new InvalidOperationException("No hay platillos con ingredientes planificados para esa semana.");

        var previousAutoItems = await dbContext
            .ShoppingItems.Where(s => s.IsAutoGenerated && s.GeneratedForWeekStart == weekStart)
            .ToListAsync(cancellationToken);
        foreach (var item in previousAutoItems)
            dbContext.ShoppingItems.Remove(item);

        var consolidated = plannedIngredients
            .GroupBy(i => (Name: i.Name.Trim().ToLowerInvariant(), i.Unit))
            .Select(g =>
                ShoppingItem.CreateGenerated(
                    tenantService.HouseholdId,
                    // Keep the casing of the first occurrence for display
                    g.First().Name.Trim(),
                    g.Sum(i => i.Amount),
                    g.Key.Unit,
                    weekStart
                )
            )
            .OrderBy(s => s.Name)
            .ToList();

        foreach (var item in consolidated)
            dbContext.ShoppingItems.Add(item);

        await dbContext.SaveChangesAsync(cancellationToken);
        return [.. consolidated.Select(i => i.ToDto())];
    }
}
