using ComeRico.Core.Domain.Entities;
using ComeRico.Core.Interfaces;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace ComeRico.Core.Features.Shopping.Queries;

public sealed record GetShoppingItemsQuery : IRequest<IReadOnlyList<ShoppingItemDto>>;

public sealed record ShoppingItemDto(
    Guid Id,
    string Name,
    decimal? Amount,
    MeasurementUnit? Unit,
    bool IsPurchased,
    bool IsAutoGenerated,
    DateOnly? GeneratedForWeekStart,
    DateTime CreatedAt
);

public static class ShoppingItemDtoMapper
{
    public static ShoppingItemDto ToDto(this ShoppingItem item) =>
        new(
            item.Id,
            item.Name,
            item.Amount,
            item.Unit,
            item.IsPurchased,
            item.IsAutoGenerated,
            item.GeneratedForWeekStart,
            item.CreatedAt
        );
}

public sealed class GetShoppingItemsQueryHandler(IAppDbContext dbContext)
    : IRequestHandler<GetShoppingItemsQuery, IReadOnlyList<ShoppingItemDto>>
{
    public async Task<IReadOnlyList<ShoppingItemDto>> Handle(GetShoppingItemsQuery request, CancellationToken cancellationToken)
    {
        var items = await dbContext.ShoppingItems.OrderBy(s => s.IsPurchased).ThenBy(s => s.Name).ToListAsync(cancellationToken);

        return [.. items.Select(i => i.ToDto())];
    }
}
