# Provider tokens (Neon, Cloudflare, Vercel) live in Infisical, not
# tfvars, fetched via `ephemeral "infisical_secret"` (one resource per
# secret — the provider doesn't expose a bulk ephemeral lookup) since they
# only ever flow into `provider` blocks (versions.tf) — ephemeral values
# are never written to state or plan files.
#
# CRON_SECRET and the R2 credentials go the other direction: generated by
# Terraform (main.tf, r2.tf) and written *into* Infisical via
# `resource "infisical_secret"`, so they're discoverable outside this
# Terraform run (e.g. `infisical run` for local scripts) even though the
# app_settings they land in (azurerm_linux_web_app.api, a plain map
# attribute with no write-only variant) use the local/resource values
# directly, not a round-trip back through Infisical.
#
# All reads/writes target the same project, mapping the Terraform
# workspace (dev/default) to an Infisical environment slug (dev/prod).

locals {
  infisical_env_slug = terraform.workspace == "default" ? "prod" : terraform.workspace
}

ephemeral "infisical_secret" "neon_api_key" {
  name         = "NEON_API_KEY"
  env_slug     = local.infisical_env_slug
  folder_path  = "/"
  workspace_id = var.infisical_project_id
}

ephemeral "infisical_secret" "cloudflare_api_token" {
  name         = "CLOUDFLARE_API_TOKEN"
  env_slug     = local.infisical_env_slug
  folder_path  = "/"
  workspace_id = var.infisical_project_id
}

ephemeral "infisical_secret" "vercel_api_token" {
  name         = "VERCEL_API_TOKEN"
  env_slug     = local.infisical_env_slug
  folder_path  = "/"
  workspace_id = var.infisical_project_id
}
