/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as OgImageRouteImport } from './routes/og-image'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as IconsFaviconDotpngRouteImport } from './routes/_icons/favicon[.]png'
import { Route as IconsFaviconDotsvgRouteImport } from './routes/_icons/favicon[.]svg'
import { Route as IconsIcon192DotpngRouteImport } from './routes/_icons/icon-192[.]png'
import { Route as IconsIcon512DotpngRouteImport } from './routes/_icons/icon-512[.]png'
import { Route as PrivateHouseholdRouteRouteImport } from './routes/_private/_household/route'
import { Route as PrivateHouseholdRouteImport } from './routes/_private/household'
import { Route as PrivateSettingsRouteImport } from './routes/_private/settings'
import { Route as PrivateHouseholdDishesRouteImport } from './routes/_private/_household/dishes'
import { Route as PrivateHouseholdMealPlanRouteImport } from './routes/_private/_household/meal-plan'
import { Route as PrivateHouseholdShoppingRouteImport } from './routes/_private/_household/shopping'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const OgImageRoute = OgImageRouteImport.update({
  id: '/og-image',
  path: '/og-image',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const IconsFaviconDotpngRoute = IconsFaviconDotpngRouteImport.update({
  id: '/_icons/favicon.png',
  path: '/favicon.png',
  getParentRoute: () => rootRouteImport,
} as any)
const IconsFaviconDotsvgRoute = IconsFaviconDotsvgRouteImport.update({
  id: '/_icons/favicon.svg',
  path: '/favicon.svg',
  getParentRoute: () => rootRouteImport,
} as any)
const IconsIcon192DotpngRoute = IconsIcon192DotpngRouteImport.update({
  id: '/_icons/icon-192.png',
  path: '/icon-192.png',
  getParentRoute: () => rootRouteImport,
} as any)
const IconsIcon512DotpngRoute = IconsIcon512DotpngRouteImport.update({
  id: '/_icons/icon-512.png',
  path: '/icon-512.png',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateHouseholdRouteRoute = PrivateHouseholdRouteRouteImport.update({
  id: '/_household',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateHouseholdRoute = PrivateHouseholdRouteImport.update({
  id: '/household',
  path: '/household',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateSettingsRoute = PrivateSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateHouseholdDishesRoute = PrivateHouseholdDishesRouteImport.update({
  id: '/dishes',
  path: '/dishes',
  getParentRoute: () => PrivateHouseholdRouteRoute,
} as any)
const PrivateHouseholdMealPlanRoute =
  PrivateHouseholdMealPlanRouteImport.update({
    id: '/meal-plan',
    path: '/meal-plan',
    getParentRoute: () => PrivateHouseholdRouteRoute,
  } as any)
const PrivateHouseholdShoppingRoute =
  PrivateHouseholdShoppingRouteImport.update({
    id: '/shopping',
    path: '/shopping',
    getParentRoute: () => PrivateHouseholdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/og-image': typeof OgImageRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/favicon.png': typeof IconsFaviconDotpngRoute
  '/favicon.svg': typeof IconsFaviconDotsvgRoute
  '/icon-192.png': typeof IconsIcon192DotpngRoute
  '/icon-512.png': typeof IconsIcon512DotpngRoute
  '/household': typeof PrivateHouseholdRoute
  '/settings': typeof PrivateSettingsRoute
  '/dishes': typeof PrivateHouseholdDishesRoute
  '/meal-plan': typeof PrivateHouseholdMealPlanRoute
  '/shopping': typeof PrivateHouseholdShoppingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/og-image': typeof OgImageRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/favicon.png': typeof IconsFaviconDotpngRoute
  '/favicon.svg': typeof IconsFaviconDotsvgRoute
  '/icon-192.png': typeof IconsIcon192DotpngRoute
  '/icon-512.png': typeof IconsIcon512DotpngRoute
  '/household': typeof PrivateHouseholdRoute
  '/settings': typeof PrivateSettingsRoute
  '/dishes': typeof PrivateHouseholdDishesRoute
  '/meal-plan': typeof PrivateHouseholdMealPlanRoute
  '/shopping': typeof PrivateHouseholdShoppingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_private': typeof PrivateRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/og-image': typeof OgImageRoute
  '/_private/_household': typeof PrivateHouseholdRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_icons/favicon.png': typeof IconsFaviconDotpngRoute
  '/_icons/favicon.svg': typeof IconsFaviconDotsvgRoute
  '/_icons/icon-192.png': typeof IconsIcon192DotpngRoute
  '/_icons/icon-512.png': typeof IconsIcon512DotpngRoute
  '/_private/household': typeof PrivateHouseholdRoute
  '/_private/settings': typeof PrivateSettingsRoute
  '/_private/_household/dishes': typeof PrivateHouseholdDishesRoute
  '/_private/_household/meal-plan': typeof PrivateHouseholdMealPlanRoute
  '/_private/_household/shopping': typeof PrivateHouseholdShoppingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/og-image'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/favicon.png'
    | '/favicon.svg'
    | '/icon-192.png'
    | '/icon-512.png'
    | '/household'
    | '/settings'
    | '/dishes'
    | '/meal-plan'
    | '/shopping'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/og-image'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/favicon.png'
    | '/favicon.svg'
    | '/icon-192.png'
    | '/icon-512.png'
    | '/household'
    | '/settings'
    | '/dishes'
    | '/meal-plan'
    | '/shopping'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_private'
    | '/about'
    | '/og-image'
    | '/_private/_household'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_icons/favicon.png'
    | '/_icons/favicon.svg'
    | '/_icons/icon-192.png'
    | '/_icons/icon-512.png'
    | '/_private/household'
    | '/_private/settings'
    | '/_private/_household/dishes'
    | '/_private/_household/meal-plan'
    | '/_private/_household/shopping'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  OgImageRoute: typeof OgImageRoute
  IconsFaviconDotpngRoute: typeof IconsFaviconDotpngRoute
  IconsFaviconDotsvgRoute: typeof IconsFaviconDotsvgRoute
  IconsIcon192DotpngRoute: typeof IconsIcon192DotpngRoute
  IconsIcon512DotpngRoute: typeof IconsIcon512DotpngRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og-image': {
      id: '/og-image'
      path: '/og-image'
      fullPath: '/og-image'
      preLoaderRoute: typeof OgImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_icons/favicon.png': {
      id: '/_icons/favicon.png'
      path: '/favicon.png'
      fullPath: '/favicon.png'
      preLoaderRoute: typeof IconsFaviconDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_icons/favicon.svg': {
      id: '/_icons/favicon.svg'
      path: '/favicon.svg'
      fullPath: '/favicon.svg'
      preLoaderRoute: typeof IconsFaviconDotsvgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_icons/icon-192.png': {
      id: '/_icons/icon-192.png'
      path: '/icon-192.png'
      fullPath: '/icon-192.png'
      preLoaderRoute: typeof IconsIcon192DotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_icons/icon-512.png': {
      id: '/_icons/icon-512.png'
      path: '/icon-512.png'
      fullPath: '/icon-512.png'
      preLoaderRoute: typeof IconsIcon512DotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/_household': {
      id: '/_private/_household'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateHouseholdRouteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/household': {
      id: '/_private/household'
      path: '/household'
      fullPath: '/household'
      preLoaderRoute: typeof PrivateHouseholdRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/settings': {
      id: '/_private/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof PrivateSettingsRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/_household/dishes': {
      id: '/_private/_household/dishes'
      path: '/dishes'
      fullPath: '/dishes'
      preLoaderRoute: typeof PrivateHouseholdDishesRouteImport
      parentRoute: typeof PrivateHouseholdRouteRoute
    }
    '/_private/_household/meal-plan': {
      id: '/_private/_household/meal-plan'
      path: '/meal-plan'
      fullPath: '/meal-plan'
      preLoaderRoute: typeof PrivateHouseholdMealPlanRouteImport
      parentRoute: typeof PrivateHouseholdRouteRoute
    }
    '/_private/_household/shopping': {
      id: '/_private/_household/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof PrivateHouseholdShoppingRouteImport
      parentRoute: typeof PrivateHouseholdRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PrivateHouseholdRouteRouteChildren {
  PrivateHouseholdDishesRoute: typeof PrivateHouseholdDishesRoute
  PrivateHouseholdMealPlanRoute: typeof PrivateHouseholdMealPlanRoute
  PrivateHouseholdShoppingRoute: typeof PrivateHouseholdShoppingRoute
}

const PrivateHouseholdRouteRouteChildren: PrivateHouseholdRouteRouteChildren = {
  PrivateHouseholdDishesRoute: PrivateHouseholdDishesRoute,
  PrivateHouseholdMealPlanRoute: PrivateHouseholdMealPlanRoute,
  PrivateHouseholdShoppingRoute: PrivateHouseholdShoppingRoute,
}

const PrivateHouseholdRouteRouteWithChildren =
  PrivateHouseholdRouteRoute._addFileChildren(
    PrivateHouseholdRouteRouteChildren,
  )

interface PrivateRouteRouteChildren {
  PrivateHouseholdRouteRoute: typeof PrivateHouseholdRouteRouteWithChildren
  PrivateHouseholdRoute: typeof PrivateHouseholdRoute
  PrivateSettingsRoute: typeof PrivateSettingsRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateHouseholdRouteRoute: PrivateHouseholdRouteRouteWithChildren,
  PrivateHouseholdRoute: PrivateHouseholdRoute,
  PrivateSettingsRoute: PrivateSettingsRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  OgImageRoute: OgImageRoute,
  IconsFaviconDotpngRoute: IconsFaviconDotpngRoute,
  IconsFaviconDotsvgRoute: IconsFaviconDotsvgRoute,
  IconsIcon192DotpngRoute: IconsIcon192DotpngRoute,
  IconsIcon512DotpngRoute: IconsIcon512DotpngRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
