/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RouletteRouteImport } from './routes/roulette'
import { Route as HouseholdRouteImport } from './routes/household'
import { Route as AboutRouteImport } from './routes/about'
import { Route as HouseholdRouteRouteImport } from './routes/_household/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HouseholdShoppingRouteImport } from './routes/_household/shopping'
import { Route as HouseholdMealPlanRouteImport } from './routes/_household/meal-plan'
import { Route as HouseholdDishesRouteImport } from './routes/_household/dishes'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'

const RouletteRoute = RouletteRouteImport.update({
  id: '/roulette',
  path: '/roulette',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdRoute = HouseholdRouteImport.update({
  id: '/household',
  path: '/household',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdRouteRoute = HouseholdRouteRouteImport.update({
  id: '/_household',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdShoppingRoute = HouseholdShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => HouseholdRouteRoute,
} as any)
const HouseholdMealPlanRoute = HouseholdMealPlanRouteImport.update({
  id: '/meal-plan',
  path: '/meal-plan',
  getParentRoute: () => HouseholdRouteRoute,
} as any)
const HouseholdDishesRoute = HouseholdDishesRouteImport.update({
  id: '/dishes',
  path: '/dishes',
  getParentRoute: () => HouseholdRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/household': typeof HouseholdRoute
  '/roulette': typeof RouletteRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/dishes': typeof HouseholdDishesRoute
  '/meal-plan': typeof HouseholdMealPlanRoute
  '/shopping': typeof HouseholdShoppingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/household': typeof HouseholdRoute
  '/roulette': typeof RouletteRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/dishes': typeof HouseholdDishesRoute
  '/meal-plan': typeof HouseholdMealPlanRoute
  '/shopping': typeof HouseholdShoppingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_household': typeof HouseholdRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/household': typeof HouseholdRoute
  '/roulette': typeof RouletteRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_household/dishes': typeof HouseholdDishesRoute
  '/_household/meal-plan': typeof HouseholdMealPlanRoute
  '/_household/shopping': typeof HouseholdShoppingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/household'
    | '/roulette'
    | '/login'
    | '/register'
    | '/dishes'
    | '/meal-plan'
    | '/shopping'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/household'
    | '/roulette'
    | '/login'
    | '/register'
    | '/dishes'
    | '/meal-plan'
    | '/shopping'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_household'
    | '/about'
    | '/household'
    | '/roulette'
    | '/_auth/login'
    | '/_auth/register'
    | '/_household/dishes'
    | '/_household/meal-plan'
    | '/_household/shopping'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  HouseholdRouteRoute: typeof HouseholdRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  HouseholdRoute: typeof HouseholdRoute
  RouletteRoute: typeof RouletteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roulette': {
      id: '/roulette'
      path: '/roulette'
      fullPath: '/roulette'
      preLoaderRoute: typeof RouletteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/household': {
      id: '/household'
      path: '/household'
      fullPath: '/household'
      preLoaderRoute: typeof HouseholdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_household': {
      id: '/_household'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HouseholdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_household/shopping': {
      id: '/_household/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof HouseholdShoppingRouteImport
      parentRoute: typeof HouseholdRouteRoute
    }
    '/_household/meal-plan': {
      id: '/_household/meal-plan'
      path: '/meal-plan'
      fullPath: '/meal-plan'
      preLoaderRoute: typeof HouseholdMealPlanRouteImport
      parentRoute: typeof HouseholdRouteRoute
    }
    '/_household/dishes': {
      id: '/_household/dishes'
      path: '/dishes'
      fullPath: '/dishes'
      preLoaderRoute: typeof HouseholdDishesRouteImport
      parentRoute: typeof HouseholdRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface HouseholdRouteRouteChildren {
  HouseholdDishesRoute: typeof HouseholdDishesRoute
  HouseholdMealPlanRoute: typeof HouseholdMealPlanRoute
  HouseholdShoppingRoute: typeof HouseholdShoppingRoute
}

const HouseholdRouteRouteChildren: HouseholdRouteRouteChildren = {
  HouseholdDishesRoute: HouseholdDishesRoute,
  HouseholdMealPlanRoute: HouseholdMealPlanRoute,
  HouseholdShoppingRoute: HouseholdShoppingRoute,
}

const HouseholdRouteRouteWithChildren = HouseholdRouteRoute._addFileChildren(
  HouseholdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  HouseholdRouteRoute: HouseholdRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  HouseholdRoute: HouseholdRoute,
  RouletteRoute: RouletteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
