/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as HouseholdRouteRouteImport } from './routes/_household/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as HouseholdRouteImport } from './routes/household'
import { Route as OgImageRouteImport } from './routes/og-image'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as HouseholdDishesRouteImport } from './routes/_household/dishes'
import { Route as HouseholdMealPlanRouteImport } from './routes/_household/meal-plan'
import { Route as HouseholdShoppingRouteImport } from './routes/_household/shopping'
import { Route as IconsFaviconDotpngRouteImport } from './routes/_icons/favicon[.]png'
import { Route as IconsFaviconDotsvgRouteImport } from './routes/_icons/favicon[.]svg'
import { Route as IconsIcon192DotpngRouteImport } from './routes/_icons/icon-192[.]png'
import { Route as IconsIcon512DotpngRouteImport } from './routes/_icons/icon-512[.]png'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdRouteRoute = HouseholdRouteRouteImport.update({
  id: '/_household',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdRoute = HouseholdRouteImport.update({
  id: '/household',
  path: '/household',
  getParentRoute: () => rootRouteImport,
} as any)
const OgImageRoute = OgImageRouteImport.update({
  id: '/og-image',
  path: '/og-image',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const HouseholdDishesRoute = HouseholdDishesRouteImport.update({
  id: '/dishes',
  path: '/dishes',
  getParentRoute: () => HouseholdRouteRoute,
} as any)
const HouseholdMealPlanRoute = HouseholdMealPlanRouteImport.update({
  id: '/meal-plan',
  path: '/meal-plan',
  getParentRoute: () => HouseholdRouteRoute,
} as any)
const HouseholdShoppingRoute = HouseholdShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => HouseholdRouteRoute,
} as any)
const IconsFaviconDotpngRoute = IconsFaviconDotpngRouteImport.update({
  id: '/_icons/favicon.png',
  path: '/favicon.png',
  getParentRoute: () => rootRouteImport,
} as any)
const IconsFaviconDotsvgRoute = IconsFaviconDotsvgRouteImport.update({
  id: '/_icons/favicon.svg',
  path: '/favicon.svg',
  getParentRoute: () => rootRouteImport,
} as any)
const IconsIcon192DotpngRoute = IconsIcon192DotpngRouteImport.update({
  id: '/_icons/icon-192.png',
  path: '/icon-192.png',
  getParentRoute: () => rootRouteImport,
} as any)
const IconsIcon512DotpngRoute = IconsIcon512DotpngRouteImport.update({
  id: '/_icons/icon-512.png',
  path: '/icon-512.png',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/household': typeof HouseholdRoute
  '/og-image': typeof OgImageRoute
  '/settings': typeof SettingsRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/dishes': typeof HouseholdDishesRoute
  '/meal-plan': typeof HouseholdMealPlanRoute
  '/shopping': typeof HouseholdShoppingRoute
  '/favicon.png': typeof IconsFaviconDotpngRoute
  '/favicon.svg': typeof IconsFaviconDotsvgRoute
  '/icon-192.png': typeof IconsIcon192DotpngRoute
  '/icon-512.png': typeof IconsIcon512DotpngRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/household': typeof HouseholdRoute
  '/og-image': typeof OgImageRoute
  '/settings': typeof SettingsRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/dishes': typeof HouseholdDishesRoute
  '/meal-plan': typeof HouseholdMealPlanRoute
  '/shopping': typeof HouseholdShoppingRoute
  '/favicon.png': typeof IconsFaviconDotpngRoute
  '/favicon.svg': typeof IconsFaviconDotsvgRoute
  '/icon-192.png': typeof IconsIcon192DotpngRoute
  '/icon-512.png': typeof IconsIcon512DotpngRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_household': typeof HouseholdRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/household': typeof HouseholdRoute
  '/og-image': typeof OgImageRoute
  '/settings': typeof SettingsRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_household/dishes': typeof HouseholdDishesRoute
  '/_household/meal-plan': typeof HouseholdMealPlanRoute
  '/_household/shopping': typeof HouseholdShoppingRoute
  '/_icons/favicon.png': typeof IconsFaviconDotpngRoute
  '/_icons/favicon.svg': typeof IconsFaviconDotsvgRoute
  '/_icons/icon-192.png': typeof IconsIcon192DotpngRoute
  '/_icons/icon-512.png': typeof IconsIcon512DotpngRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/household'
    | '/og-image'
    | '/settings'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dishes'
    | '/meal-plan'
    | '/shopping'
    | '/favicon.png'
    | '/favicon.svg'
    | '/icon-192.png'
    | '/icon-512.png'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/household'
    | '/og-image'
    | '/settings'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dishes'
    | '/meal-plan'
    | '/shopping'
    | '/favicon.png'
    | '/favicon.svg'
    | '/icon-192.png'
    | '/icon-512.png'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_household'
    | '/about'
    | '/household'
    | '/og-image'
    | '/settings'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_household/dishes'
    | '/_household/meal-plan'
    | '/_household/shopping'
    | '/_icons/favicon.png'
    | '/_icons/favicon.svg'
    | '/_icons/icon-192.png'
    | '/_icons/icon-512.png'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  HouseholdRouteRoute: typeof HouseholdRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  HouseholdRoute: typeof HouseholdRoute
  OgImageRoute: typeof OgImageRoute
  SettingsRoute: typeof SettingsRoute
  IconsFaviconDotpngRoute: typeof IconsFaviconDotpngRoute
  IconsFaviconDotsvgRoute: typeof IconsFaviconDotsvgRoute
  IconsIcon192DotpngRoute: typeof IconsIcon192DotpngRoute
  IconsIcon512DotpngRoute: typeof IconsIcon512DotpngRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_household': {
      id: '/_household'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HouseholdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/household': {
      id: '/household'
      path: '/household'
      fullPath: '/household'
      preLoaderRoute: typeof HouseholdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og-image': {
      id: '/og-image'
      path: '/og-image'
      fullPath: '/og-image'
      preLoaderRoute: typeof OgImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_household/dishes': {
      id: '/_household/dishes'
      path: '/dishes'
      fullPath: '/dishes'
      preLoaderRoute: typeof HouseholdDishesRouteImport
      parentRoute: typeof HouseholdRouteRoute
    }
    '/_household/meal-plan': {
      id: '/_household/meal-plan'
      path: '/meal-plan'
      fullPath: '/meal-plan'
      preLoaderRoute: typeof HouseholdMealPlanRouteImport
      parentRoute: typeof HouseholdRouteRoute
    }
    '/_household/shopping': {
      id: '/_household/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof HouseholdShoppingRouteImport
      parentRoute: typeof HouseholdRouteRoute
    }
    '/_icons/favicon.png': {
      id: '/_icons/favicon.png'
      path: '/favicon.png'
      fullPath: '/favicon.png'
      preLoaderRoute: typeof IconsFaviconDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_icons/favicon.svg': {
      id: '/_icons/favicon.svg'
      path: '/favicon.svg'
      fullPath: '/favicon.svg'
      preLoaderRoute: typeof IconsFaviconDotsvgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_icons/icon-192.png': {
      id: '/_icons/icon-192.png'
      path: '/icon-192.png'
      fullPath: '/icon-192.png'
      preLoaderRoute: typeof IconsIcon192DotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_icons/icon-512.png': {
      id: '/_icons/icon-512.png'
      path: '/icon-512.png'
      fullPath: '/icon-512.png'
      preLoaderRoute: typeof IconsIcon512DotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface HouseholdRouteRouteChildren {
  HouseholdDishesRoute: typeof HouseholdDishesRoute
  HouseholdMealPlanRoute: typeof HouseholdMealPlanRoute
  HouseholdShoppingRoute: typeof HouseholdShoppingRoute
}

const HouseholdRouteRouteChildren: HouseholdRouteRouteChildren = {
  HouseholdDishesRoute: HouseholdDishesRoute,
  HouseholdMealPlanRoute: HouseholdMealPlanRoute,
  HouseholdShoppingRoute: HouseholdShoppingRoute,
}

const HouseholdRouteRouteWithChildren = HouseholdRouteRoute._addFileChildren(
  HouseholdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  HouseholdRouteRoute: HouseholdRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  HouseholdRoute: HouseholdRoute,
  OgImageRoute: OgImageRoute,
  SettingsRoute: SettingsRoute,
  IconsFaviconDotpngRoute: IconsFaviconDotpngRoute,
  IconsFaviconDotsvgRoute: IconsFaviconDotsvgRoute,
  IconsIcon192DotpngRoute: IconsIcon192DotpngRoute,
  IconsIcon512DotpngRoute: IconsIcon512DotpngRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
